# Snapshot file
# Unset all aliases to avoid conflicts with functions
unalias -a 2>/dev/null || true
shopt -s expand_aliases
# Check for rg availability
if ! command -v rg >/dev/null 2>&1; then
  alias rg=''\''C:\Users\proto\AppData\Roaming\npm\node_modules\@anthropic-ai\claude-code\vendor\ripgrep\x64-win32\rg.exe'\'''
fi
export PATH='/mingw64/bin:/usr/bin:/c/Users/proto/bin:/c/Python313/Scripts:/c/Python313:/c/Users/proto/AppData/Local/Programs/cursor/resources/app/bin:/c/DatSci/Code/Python/3.12.5/Scripts:/c/DatSci/Code/Python/3.12.5:/c/DatSciX/Python Code/3.12.3/Scripts:/c/DatSciX/Python Code/3.12.3:/c/Program Files/Microsoft MPI/Bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3/libnvvp:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/libnvvp:/c/Program Files/Microsoft/jdk-11.0.16.101-hotspot/bin:/c/DatSci/Code/Python/3.11.2/Scripts:/c/DatSci/Code/Python/3.11.2:/c/DatSci/Code/Python/3.10.9/Scripts:/c/DatSci/Code/Python/3.10.9:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOW:/c/poppler:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR:/c/ProgramData/chocolatey/bin:/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin:/c/Program Files/nodejs:/c/Users/proto/scoop/shims:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/cmd:/c/Program Files/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files/dotnet:/c/DatSci/Code/Python:/c/DatSci/Code/Python/3.11.0:/c/Users/proto/AppData/Local/Microsoft/WindowsApps:/c/Users/proto/.dotnet/tools:/c/Users/proto/AppData/Local/Programs/Microsoft VS Code/bin:/c/Program Files/Azure Data Studio/bin:/c/Users/proto/AppData/Local/Pandoc:/c/Users/proto/.dotnet/tools:/c/Users/proto:/c/ProgramData/Microsoft/Windows/Start Menu/Programs/Anaconda3 (64-bit):/c/ProgramData/Microsoft/Windows/Start Menu/Programs:/c/Users/proto/AppData/Local/GitHubDesktop/bin:/c/users/proto/.local/bin:/c/Users/proto/AppData/Local/Programs/Ollama:/c/Users/proto/AppData/Local/Microsoft/WindowsApps:/c/Program Files/poppler-24.12.0:/c/DatSciX/MCP/Servers:/c/Users/proto/AppData/Roaming/npm'
